services:
  speedtest:
    image: ghcr.io/jebylinjbjob/network_test:latest
    container_name: network_speedtest
    restart: unless-stopped
    volumes:
      - .:/app/data
      - ./logs:/app/logs
      - ./charts:/app/charts
    environment:
      - TZ=Asia/Taipei
    # 如果需要使用 .env 檔案，取消下面這行註解
    # env_file:
    #   - .env
